name: "Learning Rate Sweep 3000e"
program: trainer_MGN.py
method: bayes
metric:
  name: min_test_loss
  goal: minimize
parameters:
  lr:
    min: 0.00001
    max: 0.001
  weight_decay:
    min: 0.1
    max: 0.3
 