name: "gunet_complex_crop"
program: trainer_MGN.py
method: grid        # grid, random or bayes
order: sequential   # ensures parameters are used in the order listed
metric:
  name: min_loss
  goal: minimize
parameters:
  lr:
    values: [0.00062]
  weight_decay:
    value: 1e-5
  num_layers:
    values: [3,4,5]
  hidden_dim:
    values: [8,16,24]
  batch_size:
    values: [4]
  loss_args:
    values: [5e-15] 
  model_type:
    values: ["gunet"]
  dataset_dir:
    values: ['../data_graphs/crop_vel_3h_survived_f']
  loss:
    values: ['mse']
 